# Generated by Django 4.0.6 on 2022-07-16 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('article', models.CharField(blank=True, max_length=150, null=True)),
                ('article_link', models.URLField(blank=True, null=True)),
                ('host_name', models.CharField(blank=True, max_length=150, null=True)),
                ('host_link', models.URLField(blank=True, null=True)),
                ('podcast', models.CharField(blank=True, max_length=200, null=True)),
                ('podcast_link', models.URLField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('publisher_link', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.newsitemtype')),
            ],
        ),
    ]
