# Generated by Django 4.0.5 on 2022-07-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_author_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='profile_image_description',
            field=models.CharField(blank=True, help_text='Describe the picture', max_length=50, null=True),
        ),
    ]
