# Generated by Django 4.0.5 on 2022-07-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.ImageField(help_text='160px by 160px', upload_to='images'),
        ),
    ]
