# Generated by Django 4.0.6 on 2022-07-16 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_author_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
