# Generated by Django 4.0.6 on 2022-07-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_image_description',
            field=models.CharField(default='j', help_text='Describe the picture', max_length=50),
            preserve_default=False,
        ),
    ]
