# Generated by Django 4.0.6 on 2022-07-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_newsletter_current_alter_newsletter_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
