# Generated by Django 4.0.6 on 2022-07-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_newsletter_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='about_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='current',
            field=models.BooleanField(default=False, help_text='One must be checked'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='current',
            field=models.BooleanField(default=False, help_text='One or none may be selected'),
        ),
    ]
