# Generated by Django 4.0.5 on 2022-07-11 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppearanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearance_type', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue_text', models.CharField(blank=True, max_length=150, null=True)),
                ('venue_link', models.URLField(blank=True, null=True)),
                ('venue_address', models.CharField(blank=True, max_length=200, null=True)),
                ('host_name', models.CharField(blank=True, max_length=150, null=True)),
                ('host_link', models.URLField(blank=True, null=True)),
                ('conference_name', models.CharField(blank=True, max_length=200, null=True)),
                ('conference_link', models.URLField(blank=True, null=True)),
                ('appearance_details', models.TextField(blank=True, null=True)),
                ('appearance_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appearances.appearancetype')),
            ],
        ),
    ]
