# Generated by Django 4.0.5 on 2022-07-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='venue_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
