# Generated by Django 4.0.5 on 2022-07-11 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appearances', '0002_appearance_venue_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appearance',
            name='venue_text',
        ),
    ]
