# Generated by Django 4.1.7 on 2023-03-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearances', '0003_remove_appearance_venue_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appearancetype',
            options={'ordering': ('appearance_type',)},
        ),
        migrations.AddField(
            model_name='appearance',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
